<div id="footer" class="container bg-light mt-1" style="border-radius: 5px; color:maroon;">
  <div class="row ">
   <div class="col-4">
    	<p style="font-weight: bold; text-align: center;">Information
  	     	<br><br>
  			<a href="#">Privacy Policy</a><br>
  			<a href="#">Terms and Conditions</a>
  	
   		 </p>
  </div>
  
  <div class="col-4">
  	  	<p style="font-weight: bold; text-align: center;">About
  			<br><br>
  			<a href="#">FAQs</a><br>
  		
  	
    	</p>
  </div>


  <div class="col-4">
  	<p style="font-weight: bold; text-align: center;">Follow Us
  		<br><br>
  		<a href="https://www.facebook.com" class="fa fa-facebook"></a>
		<a href="https://www.twitter.com" class="fa fa-twitter"></a>
		<a href="https://www.instagram.com/" class="fa fa-instagram"></a>
		<a href="https://www.pinterest.com.au/" class="fa fa-pinterest"></a>
  	
   	 </p>
  </div>
</div>

 

</div>
